### ISSUE TITLE
Extend readme - invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by vinibali** [JWGracht/Domoticz-Huawei-Inverter#1]
Hello @JWGracht!
Which devices are supported with this plugin?
* Could you please update the readme according to that?
* The update part on readme might contain a non touched version as "SMA" string can be found there.
I also just run into this error:
```
Oct 04 14:33:20 device domoticz[14632]: 2024-10-04 14:33:20.390  huawei_inverter: Worker thread started.                                                                  
Oct 04 14:33:20 device domoticz[14632]: 2024-10-04 14:33:20.390  Status: huawei_inverter: Entering work loop.                                                             
Oct 04 14:33:20 device domoticz[14632]: 2024-10-04 14:33:20.391  Status: huawei_inverter: Started.                                                                        
Oct 04 14:33:21 device domoticz[14632]: 2024-10-04 14:33:21.455  Status: huawei_inverter: Initialized version 0.0.1, author 'jwgracht'                                    
Oct 04 14:33:21 device domoticz[14632]: 2024-10-04 14:33:21.460  huawei_inverter: onStart called                                                                          
Oct 04 14:33:21 device domoticz[14632]: 2024-10-04 14:33:21.460  Error: huawei_inverter: Call to function 'onStart' failed, exception details:                            
Oct 04 14:33:21 device domoticz[14632]: 2024-10-04 14:33:21.465  Error: huawei_inverter: Traceback (most recent call last):                                               
Oct 04 14:33:21 device domoticz[14632]: 2024-10-04 14:33:21.465  Error: huawei_inverter:   File "/opt/domoticz/plugins/Domoticz-Huawei-Inverter/plugin.py", line 76, in on
Start                                                                                                                                                                        
Oct 04 14:33:21 device domoticz[14632]: 2024-10-04 14:33:21.465  Error: huawei_inverter:     _plugin.onStart()                                                            
Oct 04 14:33:21 device domoticz[14632]: 2024-10-04 14:33:21.465  Error: huawei_inverter:   File "/opt/domoticz/plugins/Domoticz-Huawei-Inverter/plugin.py", line 44, in on
Start                                                                                                                                                                        
Oct 04 14:33:21 device domoticz[14632]: 2024-10-04 14:33:21.465  Error: huawei_inverter:     Domoticz.Debugging(int(Parameters["Mode6"]))                                 
Oct 04 14:33:21 device domoticz[14632]: 2024-10-04 14:33:21.465  Error: huawei_inverter:                        ^^^^^^^^^^^^^^^^^^^^^^^^                                  
Oct 04 14:33:21 device domoticz[14632]: 2024-10-04 14:33:21.465  Error: huawei_inverter: ValueError: invalid literal for int() with base 10: ''                           
Oct 04 14:33:30 device domoticz[14632]: 2024-10-04 14:33:30.076  huawei_inverter: onHeartbeat called
```
which was probably solved by:
```
$ git diff
diff --git a/plugin.py b/plugin.py
index 580597a..b787a0a 100644
--- a/plugin.py
+++ b/plugin.py
@@ -41,7 +41,7 @@ class BasePlugin:
     def onStart(self):
         Domoticz.Log("onStart called")
         if Parameters["Mode1"] != "0":
-            Domoticz.Debugging(int(Parameters["Mode6"]))
+            Domoticz.Debugging(1)
             DumpConfigToLog()
 
         #if (not "Dimmer" in Devices):
```
However still no device was found. I have a SUN2000-10KTL-M1.
BR

**Comment by JWGracht** [comment]
Hi vinibali.

I start working on this plugin, but because of other priorities I did not finish it yet. I did not expect someone would find it already. My target device is the one you have. My plan is to use HuaweiSolar python library. I used the sma domoticz plugin as boilerplate to start

**Comment by vinibali** [comment]
I had the same idea, that you took the SMA inverter as a base. I was googling around to find something as I couldn't understand the nobody have the same requirements as I do.
What is left to do?

**Comment by vinibali** [comment]
hello @JWGracht !
is there a way to work together on this? I have a SUN2000-10KTL-M1 and even with the debugged output it shows nothing:
```
Nov 03 11:36:14 localhost domoticz[5228]: 2024-11-03 11:36:14.793  huawei_inverter: Worker thread started.
Nov 03 11:36:14 localhost domoticz[5228]: 2024-11-03 11:36:14.793  Status: huawei_inverter: Started.
Nov 03 11:36:14 localhost domoticz[5228]: 2024-11-03 11:36:14.794  Status: huawei_inverter: Entering work loop.
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.721  Status: huawei_inverter: Initialized version 0.0.1, author 'jwgracht'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: onStart called
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: Debug logging mask set to: PYTHON PLUGIN QUEUE IMAGE DEVICE CONNECTION MESSAGE ALL
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'HardwareID':'5'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'HomeFolder':'/opt/domoticz/plugins/Domoticz-Huawei-Inverter/'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'StartupFolder':'/opt/domoticz/'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'UserDataFolder':'/opt/domoticz/'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'Database':'/opt/domoticz/domoticz.db'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'Language':'en'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'Version':'0.0.1'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'Author':'jwgracht'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'Name':'huawei_inverter'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'Address':'192.168.5.100'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'Port':'502'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'Key':'Domoticz-Huawei-Inverter'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'Mode1':'1'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'Mode2':'60'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'Mode6':'1'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'DomoticzVersion':'2024.7'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'DomoticzHash':'b317cfab1'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.723  huawei_inverter: 'DomoticzBuildTime':'2024-07-13 16:59:31'
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.724  huawei_inverter: Device count: 0
Nov 03 11:36:15 localhost domoticz[5228]: 2024-11-03 11:36:15.724  huawei_inverter: Acquiring GIL for 'onStartCallback'
Nov 03 11:36:24 localhost domoticz[5228]: 2024-11-03 11:36:24.040  huawei_inverter: Pushing 'onHeartbeatCallback' on to queue
Nov 03 11:36:24 localhost domoticz[5228]: 2024-11-03 11:36:24.091  huawei_inverter: Processing 'onHeartbeatCallback' message
Nov 03 11:36:24 localhost domoticz[5228]: 2024-11-03 11:36:24.091  huawei_inverter: Acquiring GIL for 'onHeartbeatCallback'
Nov 03 11:36:24 localhost domoticz[5228]: 2024-11-03 11:36:24.091  huawei_inverter: Calling message handler 'onHeartbeat' on 'module' type object.
Nov 03 11:36:24 localhost domoticz[5228]: 2024-11-03 11:36:24.091  huawei_inverter: onHeartbeat called
Nov 03 11:36:24 localhost domoticz[5228]: 2024-11-03 11:36:24.091  huawei_inverter: Acquiring GIL for 'onHeartbeatCallback'
```
My modbus port is open in the FusionSolar application:
```
$ nmap -p 502 192.168.5.100
Starting Nmap 7.95 ( https://nmap.org ) at 2024-11-03 11:37 CET
Nmap scan report for 192.168.5.100
Host is up (0.0047s latency).

PORT    STATE SERVICE
502/tcp open  mbap

Nmap done: 1 IP address (1 host up) scanned in 0.33 seconds
```
Also the firmwares are on the latest version, which Domoticz version are you using?
BR

**Comment by JWGracht** [comment]
I have actually very limited time at the moment. I am planning to continue in about a month.
What is also very interesting, I saw that the latest firmware of the interverter also supports sunspec protocol. For Solaredge they are using this https://github.com/tjko/sunspec-monitor maybe this also can be reused for the Huawei inverter.

**Comment by vinibali** [comment]
How I was looking at the device settings, the sunspec protocol is only supported in the RS485 connector. That might be a not well defined part of the UI, but on the TCP I can use only the modbus protocol.

**Comment by JWGracht** [comment]
I have some results.
I tried the lib from https://github.com/wlcrs/huawei-solar-lib

When I do the following I actually got the information from my inverter
```
import asyncio
from huawei_solar import HuaweiSolarBridge
from huawei_solar import register_names as rn

async def test():
    bridge = await HuaweiSolarBridge.create(host="my_ip", port=502, slave_id=1)
    print(bridge.model_name)
    print(bridge.serial_number)

asyncio.run(test())
```
So I think this lib can be used to build the domoticz plugin

**Comment by JWGracht** [comment]
And with the following code I get a lot of data from the inverted. Takes arround 1 minute to collect all data.
```
import asyncio
from datetime import datetime
from huawei_solar import HuaweiSolarBridge
from huawei_solar import register_names as rn

async def test():
    bridge = await HuaweiSolarBridge.create(host="my_ip", port=502, slave_id=1)
    print("Generic registers:")
    print(await bridge.batch_update([rn.MODEL_NAME, rn.SERIAL_NUMBER, rn.PN, rn.FIRMWARE_VERSION, rn.SOFTWARE_VERSION, rn.PROTOCOL_VERSION_MODBUS, rn.MODEL_ID, rn.NB_PV_STRINGS, rn.NB_MPP_TRACKS, rn.RATED_POWER, rn.P_MAX, rn.S_MAX, rn.Q_MAX_OUT, rn.Q_MAX_IN, rn.P_MAX_REAL, rn.S_MAX_REAL, rn.PRODUCT_SALES_AREA, rn.GRID_STANDARD_CODE_PROTOCOL_VERSION, rn.NUMBER_OF_PACKAGES_TO_BE_UPGRADED, rn.SUBDEVICE_SUPPORT_FLAG, rn.SUBDEVICE_IN_POSITION_FLAG, rn.FEATURE_MASK_1, rn.FEATURE_MASK_2, rn.FEATURE_MASK_3, rn.FEATURE_MASK_4, rn.OFFERING_NAME_OF_SOUTHBOUND_DEVICE_1, rn.OFFERING_NAME_OF_SOUTHBOUND_DEVICE_2, rn.OFFERING_NAME_OF_SOUTHBOUND_DEVICE_3, rn.HARDWARE_VERSION, rn.MONITORING_BOARD_SN, rn.MONITORING_SOFTWARE_VERSION, rn.MASTER_DSP_VERSION, rn.CPLD_VERSION, rn.AFCI_VERSION, rn.DC_MBUS_VERSION, rn.REGKEY, rn.STATE_1, rn.STATE_2, rn.STATE_3, rn.ALARM_1, rn.ALARM_2, rn.ALARM_3, rn.INPUT_POWER, rn.LINE_VOLTAGE_A_B, rn.LINE_VOLTAGE_B_C, rn.LINE_VOLTAGE_C_A, rn.PHASE_A_VOLTAGE, rn.PHASE_B_VOLTAGE, rn.PHASE_C_VOLTAGE, rn.PHASE_A_CURRENT, rn.PHASE_B_CURRENT, rn.PHASE_C_CURRENT, rn.DAY_ACTIVE_POWER_PEAK, rn.ACTIVE_POWER, rn.REACTIVE_POWER, rn.POWER_FACTOR, rn.GRID_FREQUENCY, rn.EFFICIENCY, rn.INTERNAL_TEMPERATURE, rn.INSULATION_RESISTANCE, rn.DEVICE_STATUS, rn.FAULT_CODE, rn.STARTUP_TIME, rn.SHUTDOWN_TIME, rn.ACTIVE_POWER_FAST, rn.ACCUMULATED_YIELD_ENERGY, rn.TOTAL_DC_INPUT_POWER, rn.CURRENT_ELECTRICITY_GENERATION_STATISTICS_TIME, rn.HOURLY_YIELD_ENERGY, rn.DAILY_YIELD_ENERGY, rn.MONTHLY_YIELD_ENERGY, rn.YEARLY_YIELD_ENERGY, rn.LATEST_ACTIVE_ALARM_SN, rn.LATEST_HISTORICAL_ALARM_SN, rn.TOTAL_BUS_VOLTAGE, rn.MAX_PV_VOLTAGE, rn.MIN_PV_VOLTAGE, rn.AVERAGE_PV_NEGATIVE_VOLTAGE_TO_GROUND, rn.MIN_PV_NEGATIVE_VOLTAGE_TO_GROUND, rn.MAX_PV_NEGATIVE_VOLTAGE_TO_GROUND, rn.INVERTER_TO_PE_VOLTAGE_TOLERANCE, rn.ISO_FEATURE_INFORMATION, rn.BUILTIN_PID_RUNNING_STATUS, rn.PV_NEGATIVE_VOLTAGE_TO_GROUND, rn.CUMULATIVE_DC_ENERGY_YIELD_MPPT1, rn.CUMULATIVE_DC_ENERGY_YIELD_MPPT2, rn.CUMULATIVE_DC_ENERGY_YIELD_MPPT3, rn.CUMULATIVE_DC_ENERGY_YIELD_MPPT4, rn.CAPBANK_RUNNING_TIME, rn.INTERNAL_FAN_1_RUNNING_TIME, rn.INV_MODULE_A_TEMP, rn.INV_MODULE_B_TEMP, rn.INV_MODULE_C_TEMP, rn.ANTI_REVERSE_MODULE_1_TEMP, rn.OUTPUT_BOARD_RELAY_AMBIENT_TEMP_MAX, rn.ANTI_REVERSE_MODULE_2_TEMP, rn.DC_TERMINAL_1_2_MAX_TEMP, rn.AC_TERMINAL_1_2_3_MAX_TEMP, rn.PHASE_A_DC_COMPONENT_DCI, rn.PHASE_B_DC_COMPONENT_DCI, rn.PHASE_C_DC_COMPONENT_DCI, rn.LEAKAGE_CURRENT_RCD, rn.POSITIVE_BUS_VOLTAGE, rn.NEGATIVE_BUS_VOLTAGE, rn.BUS_NEGATIVE_VOLTAGE_TO_GROUND, rn.NB_OPTIMIZERS, rn.NB_ONLINE_OPTIMIZERS, rn.SYSTEM_TIME, rn.Q_U_CHARACTERISTIC_CURVE_MODEL, rn.Q_U_SCHEDULING_TRIGGER_POWER_PERCENTAGE, rn.POWER_FACTOR_2, rn.REACTIVE_POWER_COMPENSATION, rn.REACTIVE_POWER_ADJUSTMENT_TIME, rn.ACTIVE_POWER_PERCENTAGE_DERATING, rn.ACTIVE_POWER_FIXED_VALUE_DERATING, rn.REACTIVE_POWER_COMPENSATION_AT_NIGHT, rn.FIXED_REACTIVE_POWER_AT_NIGHT, rn.CHARACTERISTIC_CURVE_REACTIVE_POWER_ADJUSTMENT_TIME, rn.PERCENT_APPARENT_POWER, rn.Q_U_SCHEDULING_EXIT_POWER_PERCENTAGE, rn.GRID_CODE, rn.MPPT_MULTIMODAL_SCANNING, rn.MPPT_SCANNING_INTERVAL, rn.MPPT_PREDICTED_POWER, rn.TIME_ZONE, rn.WLAN_WAKEUP]))
    print("PV registers:")
    print(await bridge.batch_update([rn.PV_01_VOLTAGE, rn.PV_01_CURRENT, rn.PV_02_VOLTAGE, rn.PV_02_CURRENT, rn.PV_03_VOLTAGE, rn.PV_03_CURRENT, rn.PV_04_VOLTAGE, rn.PV_04_CURRENT]))
    print("Battery registers:")
    print(await bridge.batch_update([rn.STORAGE_UNIT_1_RUNNING_STATUS, rn.STORAGE_UNIT_1_CHARGE_DISCHARGE_POWER, rn.STORAGE_UNIT_1_BUS_VOLTAGE, rn.STORAGE_UNIT_1_STATE_OF_CAPACITY, rn.STORAGE_UNIT_1_WORKING_MODE_B, rn.STORAGE_UNIT_1_RATED_CHARGE_POWER, rn.STORAGE_UNIT_1_RATED_DISCHARGE_POWER, rn.STORAGE_UNIT_1_FAULT_ID, rn.STORAGE_UNIT_1_CURRENT_DAY_CHARGE_CAPACITY, rn.STORAGE_UNIT_1_CURRENT_DAY_DISCHARGE_CAPACITY, rn.STORAGE_UNIT_1_BUS_CURRENT, rn.STORAGE_UNIT_1_BATTERY_TEMPERATURE, rn.STORAGE_UNIT_1_REMAINING_CHARGE_DIS_CHARGE_TIME, rn.STORAGE_UNIT_1_DCDC_VERSION, rn.STORAGE_UNIT_1_BMS_VERSION, rn.STORAGE_MAXIMUM_CHARGE_POWER, rn.STORAGE_MAXIMUM_DISCHARGE_POWER, rn.STORAGE_UNIT_1_SERIAL_NUMBER, rn.STORAGE_UNIT_1_TOTAL_CHARGE, rn.STORAGE_UNIT_1_TOTAL_DISCHARGE, rn.STORAGE_UNIT_2_SERIAL_NUMBER, rn.STORAGE_UNIT_2_STATE_OF_CAPACITY, rn.STORAGE_UNIT_2_RUNNING_STATUS, rn.STORAGE_UNIT_2_CHARGE_DISCHARGE_POWER, rn.STORAGE_UNIT_2_CURRENT_DAY_CHARGE_CAPACITY, rn.STORAGE_UNIT_2_CURRENT_DAY_DISCHARGE_CAPACITY, rn.STORAGE_UNIT_2_BUS_VOLTAGE, rn.STORAGE_UNIT_2_BUS_CURRENT, rn.STORAGE_UNIT_2_BATTERY_TEMPERATURE, rn.STORAGE_UNIT_2_TOTAL_CHARGE, rn.STORAGE_UNIT_2_TOTAL_DISCHARGE, rn.STORAGE_RATED_CAPACITY, rn.STORAGE_STATE_OF_CAPACITY, rn.STORAGE_RUNNING_STATUS, rn.STORAGE_BUS_VOLTAGE, rn.STORAGE_BUS_CURRENT, rn.STORAGE_CHARGE_DISCHARGE_POWER, rn.STORAGE_TOTAL_CHARGE, rn.STORAGE_TOTAL_DISCHARGE, rn.STORAGE_CURRENT_DAY_CHARGE_CAPACITY, rn.STORAGE_CURRENT_DAY_DISCHARGE_CAPACITY, rn.STORAGE_UNIT_2_SOFTWARE_VERSION, rn.STORAGE_UNIT_1_SOFTWARE_VERSION, rn.STORAGE_UNIT_1_BATTERY_PACK_1_SERIAL_NUMBER, rn.STORAGE_UNIT_1_BATTERY_PACK_1_FIRMWARE_VERSION, rn.STORAGE_UNIT_1_BATTERY_PACK_1_WORKING_STATUS, rn.STORAGE_UNIT_1_BATTERY_PACK_1_STATE_OF_CAPACITY, rn.STORAGE_UNIT_1_BATTERY_PACK_1_CHARGE_DISCHARGE_POWER, rn.STORAGE_UNIT_1_BATTERY_PACK_1_VOLTAGE, rn.STORAGE_UNIT_1_BATTERY_PACK_1_CURRENT, rn.STORAGE_UNIT_1_BATTERY_PACK_1_TOTAL_CHARGE, rn.STORAGE_UNIT_1_BATTERY_PACK_1_TOTAL_DISCHARGE, rn.STORAGE_UNIT_1_BATTERY_PACK_2_SERIAL_NUMBER, rn.STORAGE_UNIT_1_BATTERY_PACK_2_FIRMWARE_VERSION, rn.STORAGE_UNIT_1_BATTERY_PACK_2_WORKING_STATUS, rn.STORAGE_UNIT_1_BATTERY_PACK_2_STATE_OF_CAPACITY, rn.STORAGE_UNIT_1_BATTERY_PACK_2_CHARGE_DISCHARGE_POWER, rn.STORAGE_UNIT_1_BATTERY_PACK_2_VOLTAGE, rn.STORAGE_UNIT_1_BATTERY_PACK_2_CURRENT, rn.STORAGE_UNIT_1_BATTERY_PACK_2_TOTAL_CHARGE, rn.STORAGE_UNIT_1_BATTERY_PACK_2_TOTAL_DISCHARGE, rn.STORAGE_UNIT_1_BATTERY_PACK_3_SERIAL_NUMBER, rn.STORAGE_UNIT_1_BATTERY_PACK_3_FIRMWARE_VERSION, rn.STORAGE_UNIT_1_BATTERY_PACK_3_WORKING_STATUS, rn.STORAGE_UNIT_1_BATTERY_PACK_3_STATE_OF_CAPACITY, rn.STORAGE_UNIT_1_BATTERY_PACK_3_CHARGE_DISCHARGE_POWER, rn.STORAGE_UNIT_1_BATTERY_PACK_3_VOLTAGE, rn.STORAGE_UNIT_1_BATTERY_PACK_3_CURRENT, rn.STORAGE_UNIT_1_BATTERY_PACK_3_TOTAL_CHARGE, rn.STORAGE_UNIT_1_BATTERY_PACK_3_TOTAL_DISCHARGE, rn.STORAGE_UNIT_2_BATTERY_PACK_1_SERIAL_NUMBER, rn.STORAGE_UNIT_2_BATTERY_PACK_1_FIRMWARE_VERSION, rn.STORAGE_UNIT_2_BATTERY_PACK_1_WORKING_STATUS, rn.STORAGE_UNIT_2_BATTERY_PACK_1_STATE_OF_CAPACITY, rn.STORAGE_UNIT_2_BATTERY_PACK_1_CHARGE_DISCHARGE_POWER, rn.STORAGE_UNIT_2_BATTERY_PACK_1_VOLTAGE, rn.STORAGE_UNIT_2_BATTERY_PACK_1_CURRENT, rn.STORAGE_UNIT_2_BATTERY_PACK_1_TOTAL_CHARGE, rn.STORAGE_UNIT_2_BATTERY_PACK_1_TOTAL_DISCHARGE, rn.STORAGE_UNIT_2_BATTERY_PACK_2_SERIAL_NUMBER, rn.STORAGE_UNIT_2_BATTERY_PACK_2_FIRMWARE_VERSION, rn.STORAGE_UNIT_2_BATTERY_PACK_2_WORKING_STATUS, rn.STORAGE_UNIT_2_BATTERY_PACK_2_STATE_OF_CAPACITY, rn.STORAGE_UNIT_2_BATTERY_PACK_2_CHARGE_DISCHARGE_POWER, rn.STORAGE_UNIT_2_BATTERY_PACK_2_VOLTAGE, rn.STORAGE_UNIT_2_BATTERY_PACK_2_CURRENT, rn.STORAGE_UNIT_2_BATTERY_PACK_2_TOTAL_CHARGE, rn.STORAGE_UNIT_2_BATTERY_PACK_2_TOTAL_DISCHARGE, rn.STORAGE_UNIT_2_BATTERY_PACK_3_SERIAL_NUMBER, rn.STORAGE_UNIT_2_BATTERY_PACK_3_FIRMWARE_VERSION, rn.STORAGE_UNIT_2_BATTERY_PACK_3_WORKING_STATUS, rn.STORAGE_UNIT_2_BATTERY_PACK_3_STATE_OF_CAPACITY, rn.STORAGE_UNIT_2_BATTERY_PACK_3_CHARGE_DISCHARGE_POWER, rn.STORAGE_UNIT_2_BATTERY_PACK_3_VOLTAGE, rn.STORAGE_UNIT_2_BATTERY_PACK_3_CURRENT, rn.STORAGE_UNIT_2_BATTERY_PACK_3_TOTAL_CHARGE, rn.STORAGE_UNIT_2_BATTERY_PACK_3_TOTAL_DISCHARGE, rn.STORAGE_UNIT_1_BATTERY_PACK_1_MAXIMUM_TEMPERATURE, rn.STORAGE_UNIT_1_BATTERY_PACK_1_MINIMUM_TEMPERATURE, rn.STORAGE_UNIT_1_BATTERY_PACK_2_MAXIMUM_TEMPERATURE, rn.STORAGE_UNIT_1_BATTERY_PACK_2_MINIMUM_TEMPERATURE, rn.STORAGE_UNIT_1_BATTERY_PACK_3_MAXIMUM_TEMPERATURE, rn.STORAGE_UNIT_1_BATTERY_PACK_3_MINIMUM_TEMPERATURE, rn.STORAGE_UNIT_2_BATTERY_PACK_1_MAXIMUM_TEMPERATURE, rn.STORAGE_UNIT_2_BATTERY_PACK_1_MINIMUM_TEMPERATURE, rn.STORAGE_UNIT_2_BATTERY_PACK_2_MAXIMUM_TEMPERATURE, rn.STORAGE_UNIT_2_BATTERY_PACK_2_MINIMUM_TEMPERATURE, rn.STORAGE_UNIT_2_BATTERY_PACK_3_MAXIMUM_TEMPERATURE, rn.STORAGE_UNIT_2_BATTERY_PACK_3_MINIMUM_TEMPERATURE, rn.STORAGE_UNIT_1_PRODUCT_MODEL, rn.STORAGE_WORKING_MODE_A, rn.STORAGE_TIME_OF_USE_PRICE, rn.STORAGE_LCOE, rn.STORAGE_MAXIMUM_CHARGING_POWER, rn.STORAGE_MAXIMUM_DISCHARGING_POWER, rn.STORAGE_POWER_LIMIT_GRID_TIED_POINT, rn.STORAGE_CHARGING_CUTOFF_CAPACITY, rn.STORAGE_DISCHARGING_CUTOFF_CAPACITY, rn.STORAGE_FORCED_CHARGING_AND_DISCHARGING_PERIOD, rn.STORAGE_FORCED_CHARGING_AND_DISCHARGING_POWER, rn.STORAGE_WORKING_MODE_SETTINGS, rn.STORAGE_CHARGE_FROM_GRID_FUNCTION, rn.STORAGE_GRID_CHARGE_CUTOFF_STATE_OF_CHARGE, rn.STORAGE_UNIT_2_PRODUCT_MODEL, rn.STORAGE_FORCIBLE_CHARGE_DISCHARGE_WRITE, rn.STORAGE_FORCIBLE_CHARGE_DISCHARGE_SOC, rn.STORAGE_BACKUP_POWER_STATE_OF_CHARGE, rn.STORAGE_UNIT_1_NO, rn.STORAGE_UNIT_2_NO, rn.STORAGE_FIXED_CHARGING_AND_DISCHARGING_PERIODS, rn.STORAGE_POWER_OF_CHARGE_FROM_GRID, rn.STORAGE_MAXIMUM_POWER_OF_CHARGE_FROM_GRID, rn.STORAGE_FORCIBLE_CHARGE_DISCHARGE_SETTING_MODE, rn.STORAGE_FORCIBLE_CHARGE_POWER, rn.STORAGE_FORCIBLE_DISCHARGE_POWER, rn.STORAGE_EXCESS_PV_ENERGY_USE_IN_TOU, rn.ACTIVE_POWER_CONTROL_MODE, rn.MAXIMUM_FEED_GRID_POWER_WATT, rn.MAXIMUM_FEED_GRID_POWER_PERCENT, rn.REMOTE_CHARGE_DISCHARGE_CONTROL_MODE, rn.DONGLE_PLANT_MAXIMUM_CHARGE_FROM_GRID_POWER, rn.BACKUP_SWITCH_TO_OFF_GRID, rn.DEFAULT_MAXIMUM_FEED_IN_POWER, rn.DEFAULT_ACTIVE_POWER_CHANGE_GRADIENT, rn.STORAGE_UNIT_1_PACK_1_NO, rn.STORAGE_UNIT_1_PACK_2_NO, rn.STORAGE_UNIT_1_PACK_3_NO, rn.STORAGE_UNIT_2_PACK_1_NO, rn.STORAGE_UNIT_2_PACK_2_NO, rn.STORAGE_UNIT_2_PACK_3_NO]))
    print("Capacity control registers:")
    print(await bridge.batch_update([rn.STORAGE_CAPACITY_CONTROL_MODE, rn.STORAGE_CAPACITY_CONTROL_SOC_PEAK_SHAVING, rn.STORAGE_CAPACITY_CONTROL_PERIODS]))
    print("Emma registers:")
    print(await bridge.batch_update([rn.EMMA]))
    print("Meter registers:")
    print(await bridge.batch_update([rn.METER_STATUS, rn.GRID_A_VOLTAGE, rn.GRID_B_VOLTAGE, rn.GRID_C_VOLTAGE, rn.ACTIVE_GRID_A_CURRENT, rn.ACTIVE_GRID_B_CURRENT, rn.ACTIVE_GRID_C_CURRENT, rn.POWER_METER_ACTIVE_POWER, rn.POWER_METER_REACTIVE_POWER, rn.ACTIVE_GRID_POWER_FACTOR, rn.ACTIVE_GRID_FREQUENCY, rn.GRID_EXPORTED_ENERGY, rn.GRID_ACCUMULATED_ENERGY, rn.GRID_ACCUMULATED_REACTIVE_POWER, rn.METER_TYPE, rn.ACTIVE_GRID_A_B_VOLTAGE, rn.ACTIVE_GRID_B_C_VOLTAGE, rn.ACTIVE_GRID_C_A_VOLTAGE, rn.ACTIVE_GRID_A_POWER, rn.ACTIVE_GRID_B_POWER, rn.ACTIVE_GRID_C_POWER, rn.METER_TYPE_CHECK]))

asyncio.run(test())
```
So we have connection. Now lets build the plugin to add all this info to Domoticz

**Comment by vinibali** [comment]
Looks much better this time. How could we set this up with Domoticz?

**Comment by JWGracht** [comment]
I pushed a test version now to Github. This one only collects DC string voltage and current. If this is working, then I will try to add more.

**Comment by vinibali** [comment]
awesome, it's now listing the:
* all string voltage and current
* all phase voltage and current
* input power (is it the one coming from the panels?)
* active power (might be converted AC on the output? - around 3% less than the input power)
* reactive power (internal consumption?)
* active_grid_[abc]_power (extra device for measuring the use of the house?)
so far it looks great in the devices list, however it's not added to the Utility tab. another step could be to integrate this into the "Energy Dashboard".
which version are you using?

**Comment by vinibali** [comment]
I also feel like, the Reading Interval sec. is not getting picked up by the script. the script is triggered every 5 seconds now.

**Comment by JWGracht** [comment]
Thanks for testing.

1. I think input power is indeed the one coming from the panels
2. I think active power is indeed the converted AC output
3. I am not sure what this reactive power is
4. Yes, I have a power meter so that's why I also added that one. Later-on I am planning to include the battery
5. Did you tried to press the green arrow in the device list? That should iclude the device to the utility tab
6. I have now added the energy meter for the energy dashboard. But since in the area I live has only a few hours daylight at the moment, I have to wait till tomorrow to test. If it is working, I will push the update tomorrow.
7. I have indeed set the reading interval to 5 seconds. "Domoticz.Heartbeat(5)" just to be sure there is enough time to receive all data. I did not test how long it takes for the inverter to send all information.

**Comment by JWGracht** [comment]
The energy meter is now also available in the latest comit.

I think this is a nice first release of the plugin and some of the data is available. Therefor I will close this issue.
you're always welcome to contribute with future releases of this plugin.

**Comment by vinibali** [comment]
Thanks for your work @JWGracht !
